//! Turn Spleen's BDF into a table the console can index.
//!
//! The font is a git submodule (`vendor/spleen`, BSD-2-Clause, Frederic
//! Cambus) and is parsed here rather than checked in as generated Rust: the
//! upstream file stays the single source of truth, its licence travels with it,
//! and updating the font is a submodule bump rather than a regenerated blob in
//! a diff.
//!
//! Only `0x20..=0x7E` is emitted. Spleen carries far more — Latin-1, box
//! drawing, Braille — and a kernel console that cannot decode UTF-8 has no way
//! to reach any of it.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::fmt::Write as _;
use std::path::PathBuf;

/// First code point emitted.
const FIRST: u8 = 0x20;
/// Last code point emitted.
const LAST: u8 = 0x7E;

fn main() {
    let bdf = PathBuf::from("vendor/spleen/spleen-8x16.bdf");
    println!("cargo:rerun-if-changed={}", bdf.display());
    println!("cargo:rerun-if-changed=build.rs");

    let text = fs::read_to_string(&bdf).unwrap_or_else(|e| {
        panic!(
            "cannot read {}: {e}\n\
             \n\
             Spleen is a git submodule. Fetch it with:\n\
             \n\
             \tgit submodule update --init crates/akuma-fbcon/vendor/spleen\n",
            bdf.display()
        )
    });

    let (width, height, glyphs) = parse(&text);
    assert_eq!(
        width, 8,
        "this generator packs one byte per row, so it needs an 8-pixel-wide font"
    );

    let mut out = String::new();
    let _ = write!(
        out,
        "// Generated by build.rs from vendor/spleen/spleen-8x16.bdf. Do not edit.\n\
         /// Pixels across one glyph.\n\
         pub const WIDTH: usize = {width};\n\
         /// Pixels down one glyph.\n\
         pub const HEIGHT: usize = {height};\n\
         /// First code point in [`GLYPHS`].\n\
         pub const FIRST: u8 = 0x{FIRST:02X};\n\
         /// Last code point in [`GLYPHS`].\n\
         pub const LAST: u8 = 0x{LAST:02X};\n\
         \n\
         /// The font, one entry per code point from [`FIRST`] to [`LAST`].\n\
         #[rustfmt::skip]\n\
         pub const GLYPHS: [[u8; HEIGHT]; (LAST - FIRST + 1) as usize] = [\n"
    );
    for c in FIRST..=LAST {
        let rows = glyphs.get(&u32::from(c)).unwrap_or_else(|| {
            panic!("spleen-8x16.bdf has no glyph for code point {c:#04x}")
        });
        assert_eq!(rows.len(), height, "glyph {c:#04x} is not {height} rows");
        let body: Vec<String> = rows.iter().map(|b| format!("0x{b:02X}")).collect();
        let _ = writeln!(out, "    [{}],", body.join(", "));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("spleen.rs");
    fs::write(&dest, out).expect("writing the generated font");
}

/// Pull the bounding box and every glyph bitmap out of a BDF.
///
/// Spleen's glyphs all carry a `BBX` identical to the font bounding box, so no
/// per-glyph placement arithmetic is needed — but that is checked rather than
/// assumed, because a font where it is not true would otherwise produce a table
/// of subtly shifted glyphs and no error.
fn parse(text: &str) -> (usize, usize, HashMap<u32, Vec<u8>>) {
    let mut fbb: Option<(usize, usize, i32, i32)> = None;
    let mut glyphs = HashMap::new();

    let mut encoding: Option<u32> = None;
    let mut bbx: Option<(usize, usize, i32, i32)> = None;
    let mut rows: Vec<u8> = Vec::new();
    let mut in_bitmap = false;

    for line in text.lines() {
        let line = line.trim_end();
        if let Some(rest) = line.strip_prefix("FONTBOUNDINGBOX ") {
            fbb = Some(quad(rest));
        } else if let Some(rest) = line.strip_prefix("ENCODING ") {
            encoding = rest.trim().parse().ok();
        } else if let Some(rest) = line.strip_prefix("BBX ") {
            bbx = Some(quad(rest));
        } else if line == "BITMAP" {
            in_bitmap = true;
            rows = Vec::new();
        } else if line == "ENDCHAR" {
            in_bitmap = false;
            if let (Some(enc), Some(b), Some(f)) = (encoding, bbx, fbb) {
                assert_eq!(
                    b, f,
                    "glyph {enc:#x} has a bounding box unlike the font's; this \
                     generator assumes a fixed-cell font"
                );
                glyphs.insert(enc, core::mem::take(&mut rows));
            }
            encoding = None;
            bbx = None;
        } else if in_bitmap && !line.is_empty() {
            let byte = u8::from_str_radix(line.trim(), 16)
                .unwrap_or_else(|e| panic!("bad bitmap row {line:?}: {e}"));
            rows.push(byte);
        }
    }

    let (w, h, _, _) = fbb.expect("BDF has no FONTBOUNDINGBOX");
    (w, h, glyphs)
}

/// Parse the four whitespace-separated numbers a `BBX`/`FONTBOUNDINGBOX` carries.
fn quad(text: &str) -> (usize, usize, i32, i32) {
    let mut fields = text.split_whitespace();
    let mut next_i = || fields.next().expect("short BBX").parse::<i32>().expect("bad BBX");
    let w = next_i();
    let h = next_i();
    let x = next_i();
    let y = next_i();
    (w as usize, h as usize, x, y)
}
