//! The one errno table, and the one place a value gets negated.
//!
//! # Why these are here
//!
//! Errno values were spelled five ways in this tree, and every spelling had the
//! same cause as the other duplications this crate exists to end: **the table
//! lived somewhere the other caller could not reach.** The bin crate kept 29
//! *pre-negated* `u64` consts private to `src/syscall/mod.rs`; `akuma-net` kept
//! 25 *positive* `i32` consts in `socket::libc_errno` because a library crate
//! cannot reach the bin crate's privates; `src/syscall/msgqueue.rs` and
//! `src/syscall/fs.rs` then grew four more pre-negated consts of their own
//! (`ENOMSG`, `E2BIG`, `EROFS`) one module away from an identical definition; and
//! the remaining call sites gave up and wrote the number, either as
//! `(-(25i64)) as u64 // ENOTTY` or as `i64::from(-libc_errno::ENOMEM) as u64`.
//! 17 names were defined twice, in two representations, bridged by a
//! `neg_errno()` in the bin crate that only some of the call sites used.
//!
//! See `docs/archive/TRIM_FAT_EMBARASSING_DUPLICATIONS.md` §5.7.
//!
//! # Why this is a duplication finding and not a style preference
//!
//! In `(-(25i64)) as u64 // ENOTTY` the comment carries the meaning and the
//! number carries the behaviour, so the two drift silently and a wrong number is
//! indistinguishable from a right one at the call site. That already happened
//! here: `src/syscall/term.rs` returned `-12` (`ENOMEM`) under a comment reading
//! `// ENXIO — no terminal attached`, and the comment had been wrong for as long
//! as the line existed. CPD cannot see any of this — every instance is a
//! token-level literal.
//!
//! # The shape
//!
//! One list, in [`errno_table!`] below. It generates the positive `i32` consts
//! *and* the [`negated`] `u64` consts from the same entry, so the two
//! representations cannot disagree; [`neg_errno`] is the only negation in the
//! tree. Values are the Linux `asm-generic` numbers, which is what musl and Go
//! decode against on this target.
//!
//! # Which form to use
//!
//! - **Returning from a syscall arm:** the [`negated`] form, `x0 = -errno`. The
//!   AArch64 ABI returns the negated value in `x0` and userspace decodes it with
//!   `if ((long)ret < 0) errno = -(int)ret`.
//! - **Carrying an error inside the kernel** (a `Result<_, i32>`, a socket-layer
//!   error): the positive form, negated once at the syscall boundary with
//!   [`neg_errno`].

/// Encode a positive errno as the AArch64 syscall-ABI return value (`x0 = -errno`).
///
/// The only negation in the tree. The [`negated`] consts are generated by calling
/// this at compile time, so a hand-written `(-22i64) as u64` anywhere else is a
/// second spelling by definition.
#[inline]
#[must_use]
pub const fn neg_errno(e: i32) -> u64 {
    (-(e as i64)) as u64
}

/// Defines each errno once and derives both representations from it.
///
/// Not exported: the table is meant to be *the* table, so there is no reason for
/// another crate to instantiate a second one.
macro_rules! errno_table {
    ($($(#[$doc:meta])* $name:ident = $value:expr;)*) => {
        $($(#[$doc])* pub const $name: i32 = $value;)*

        /// The same table in the form a syscall arm returns: `x0 = -errno`.
        ///
        /// Generated from the positive consts via [`neg_errno`](super::neg_errno),
        /// so these cannot drift from their positive counterparts.
        pub mod negated {
            $($(#[$doc])* pub const $name: u64 = super::neg_errno(super::$name);)*
        }

        /// Every (name, positive value) pair, for the table-wide invariant tests.
        #[cfg(test)]
        const ALL: &[(&str, i32)] = &[$((stringify!($name), $name)),*];
    };
}

errno_table! {
    EPERM = 1;
    ENOENT = 2;
    ESRCH = 3;
    EINTR = 4;
    EIO = 5;
    E2BIG = 7;
    ENOEXEC = 8;
    EBADF = 9;
    ECHILD = 10;
    EAGAIN = 11;
    ENOMEM = 12;
    EACCES = 13;
    EFAULT = 14;
    EBUSY = 16;
    EEXIST = 17;
    ENODEV = 19;
    ENOTDIR = 20;
    EISDIR = 21;
    EINVAL = 22;
    EMFILE = 24;
    ENOTTY = 25;
    ENOSPC = 28;
    ESPIPE = 29;
    EROFS = 30;
    EPIPE = 32;
    ERANGE = 34;
    ENOSYS = 38;
    ENOTEMPTY = 39;
    ENOMSG = 42;
    /// The fd is not a socket. Returned by the AF_UNIX arms when a socket
    /// syscall lands on a pipe, a file or a tty — previously these answered
    /// `EBADF`, which tells a caller the descriptor is invalid rather than that
    /// it is the wrong *kind* of object, and sends it looking for a leak.
    ENOTSOCK = 88;
    EDESTADDRREQ = 89;
    /// A datagram larger than the socket's send buffer. The AF_UNIX framed
    /// types (`SOCK_DGRAM`/`SOCK_SEQPACKET`) must report this rather than
    /// blocking: a message that cannot fit atomically can never be sent, and a
    /// partial write is unrepresentable for a framed socket
    /// (`akuma_net::unix::plan_write`).
    EMSGSIZE = 90;
    /// The peer's socket type does not match this one's — connecting a
    /// `SOCK_STREAM` to a `SOCK_DGRAM` name, for instance. Distinct from
    /// `EPROTONOSUPPORT`: the protocol exists, this socket is the wrong type
    /// for it.
    EPROTOTYPE = 91;
    /// Returned by the extended-attribute syscall arms. Must be encoded as
    /// `x0 = -95` (`0xffff_ffa9`), never `!95` — that is `-96`
    /// ([`EPFNOSUPPORT`]) and breaks musl and Go callers.
    EOPNOTSUPP = 95;
    /// Not returned by anything; defined so the `!95` mis-encoding above has a
    /// name to be wrong *as*, which is what
    /// `eopnotsupp_encodes_as_negation_not_complement` asserts.
    EPFNOSUPPORT = 96;
    EAFNOSUPPORT = 97;
    EADDRINUSE = 98;
    EADDRNOTAVAIL = 99;
    ENETDOWN = 100;
    ECONNABORTED = 103;
    /// The peer aborted an established connection (RST). Distinct from a
    /// graceful FIN, which is `read() == 0` — see
    /// `akuma_net::socket::socket_recv`.
    ECONNRESET = 104;
    EISCONN = 106;
    ENOTCONN = 107;
    ETIMEDOUT = 110;
    ECONNREFUSED = 111;
    EALREADY = 114;
    EINPROGRESS = 115;
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The property that makes the negated form safe to hand to userspace: musl
    /// decodes with `if ((long)ret < 0) errno = -(int)ret`, so every entry must
    /// survive that round trip and must look negative when read as `i64`.
    #[test]
    fn every_negated_value_decodes_back_to_its_positive() {
        for &(name, value) in ALL {
            let encoded = neg_errno(value);
            assert!((encoded as i64) < 0, "{name} does not read as negative");
            assert_eq!(
                -(encoded as i64) as i32,
                value,
                "{name} does not survive the userspace decode"
            );
        }
    }

    /// A duplicate value is how a copy-paste in the table would present: two
    /// names returning the same number, with only one of them meaning it.
    #[test]
    fn no_two_names_share_a_value() {
        for (i, &(a_name, a_value)) in ALL.iter().enumerate() {
            for &(b_name, b_value) in &ALL[i + 1..] {
                assert_ne!(a_value, b_value, "{a_name} and {b_name} share a value");
            }
        }
    }

    /// Restates every value as a literal, deliberately duplicating the table.
    ///
    /// This is the one duplication in this module that has to stay, and it
    /// replaces something real that the merge removed. The boot tests used to
    /// declare their own `const EINVAL: u64 = (-22i64) as u64;` per test function,
    /// which — however badly it scaled to 59 copies — was an *independent*
    /// restatement of the number: a syscall returning the wrong errno failed the
    /// comparison. Those tests now import the same constant the kernel returns, so
    /// a mistyped digit here would move both sides together and every one of them
    /// would still pass. This test is where that check went.
    ///
    /// Values are the Linux `asm-generic` numbers (`asm-generic/errno-base.h` and
    /// `errno.h`), which is what musl and Go decode against on aarch64. The first
    /// 17 are additionally the names that were defined in *both* of the two tables
    /// this module replaced, at the value both of them had.
    #[test]
    fn every_value_is_the_linux_number() {
        let expected: &[(&str, i32, i32)] = &[
            // Defined in both old tables (bin crate, pre-negated; akuma-net, positive).
            ("EPERM", EPERM, 1),
            ("ENOENT", ENOENT, 2),
            ("ESRCH", ESRCH, 3),
            ("EINTR", EINTR, 4),
            ("EIO", EIO, 5),
            ("ENOEXEC", ENOEXEC, 8),
            ("EBADF", EBADF, 9),
            ("EAGAIN", EAGAIN, 11),
            ("ENOMEM", ENOMEM, 12),
            ("EACCES", EACCES, 13),
            ("EFAULT", EFAULT, 14),
            ("EEXIST", EEXIST, 17),
            ("EINVAL", EINVAL, 22),
            ("EMFILE", EMFILE, 24),
            ("EADDRINUSE", EADDRINUSE, 98),
            ("ETIMEDOUT", ETIMEDOUT, 110),
            ("EINPROGRESS", EINPROGRESS, 115),
            // Defined once in one of them.
            ("ECHILD", ECHILD, 10),
            ("ENODEV", ENODEV, 19),
            ("ENOTDIR", ENOTDIR, 20),
            ("EISDIR", EISDIR, 21),
            ("ENOSPC", ENOSPC, 28),
            ("ESPIPE", ESPIPE, 29),
            ("EPIPE", EPIPE, 32),
            ("ERANGE", ERANGE, 34),
            ("ENOSYS", ENOSYS, 38),
            ("ENOTEMPTY", ENOTEMPTY, 39),
            ("EDESTADDRREQ", EDESTADDRREQ, 89),
            // Added 2026-08-23 for the AF_UNIX socket family
            // (`akuma_net::unix`); no history under the old tables.
            ("ENOTSOCK", ENOTSOCK, 88),
            ("EMSGSIZE", EMSGSIZE, 90),
            ("EPROTOTYPE", EPROTOTYPE, 91),
            ("EAFNOSUPPORT", EAFNOSUPPORT, 97),
            ("EADDRNOTAVAIL", EADDRNOTAVAIL, 99),
            ("ENETDOWN", ENETDOWN, 100),
            ("ECONNABORTED", ECONNABORTED, 103),
            ("ECONNRESET", ECONNRESET, 104),
            ("EISCONN", EISCONN, 106),
            ("ENOTCONN", ENOTCONN, 107),
            ("ECONNREFUSED", ECONNREFUSED, 111),
            ("EALREADY", EALREADY, 114),
            // Module-local third definitions (`msgqueue.rs`, `fs.rs`) and the
            // names that only ever existed as raw literals at a call site.
            ("E2BIG", E2BIG, 7),
            ("ENOMSG", ENOMSG, 42),
            ("EROFS", EROFS, 30),
            ("ENOTTY", ENOTTY, 25),
            ("EOPNOTSUPP", EOPNOTSUPP, 95),
            ("EPFNOSUPPORT", EPFNOSUPPORT, 96),
            // Added 2026-08-23 for `sys_reattach`'s "already attached" case
            // (`box grab`'s `-d`/screen-style detach) — never existed under
            // any of the old tables, so it has no history to pin against.
            ("EBUSY", EBUSY, 16),
        ];
        for &(name, actual, want) in expected {
            assert_eq!(actual, want, "{name} is not the Linux value");
        }
        assert_eq!(
            expected.len(),
            ALL.len(),
            "a name was added to the table without being pinned here"
        );
    }

    /// The xattr arms' encoding, spelled out because the wrong one (`!95`) is a
    /// valid-looking `u64` that means a different errno.
    #[test]
    fn eopnotsupp_encodes_as_negation_not_complement() {
        assert_eq!(negated::EOPNOTSUPP, 0xffff_ffff_ffff_ffa1);
        assert_ne!(negated::EOPNOTSUPP, !95u64);
        assert_eq!(-(!95u64 as i64) as i32, EPFNOSUPPORT);
    }
}
